version: 2.1

commands:
    setup_environment:
        description: "Setup the machine environment"
        steps:
            - run: |
                  sudo apt update
                  sudo apt install -y make bash git jq docker

jobs:
    test:
        machine:
            # https://circleci.com/docs/2.0/images/linux-vm/16.04-to-20.04-migration/
            image: ubuntu-2004:202201-02
        steps:
            - setup_environment
            - checkout
            - run: make test
            - run: make test-destroy

    redhat:
        parameters:
            package:
                type: string
        machine: true
        steps:
            - setup_environment
            - checkout
            - run: docker login -u unused --password ${REDHAT_REGISTRY_KEY_NODE} scan.connect.redhat.com
            - run: make build-<<parameters.package>> redhat-verify-<<parameters.package>> VARIANT=redhat

    redhat-ciab:
        machine: true
        steps:
            - setup_environment
            - checkout
            - run: docker login -u unused --password ${REDHAT_REGISTRY_KEY_CIAB} scan.connect.redhat.com
            - run: make build-ciab redhat-verify-ciab VARIANT=redhat

    dockerhub:
        parameters:
            package:
                type: string
        machine:
            # https://circleci.com/docs/2.0/images/linux-vm/16.04-to-20.04-migration/
            image: ubuntu-2004:202201-02
        steps:
            - setup_environment
            - checkout
            - run: docker login -u ${DOCKER_HUB_USER} --password ${DOCKER_HUB_KEY}
            - run: make build-<<parameters.package>> publish-<<parameters.package>>

    gcr-public:
        parameters:
            package:
                type: string
        machine:
            # https://circleci.com/docs/2.0/images/linux-vm/16.04-to-20.04-migration/
            image: ubuntu-2004:202201-02
        steps:
            - setup_environment
            - checkout
            - run: docker login -u ${DOCKER_HUB_USER} --password ${DOCKER_HUB_KEY}
            - run: make build-<<parameters.package>> publish-<<parameters.package>>

    ubi-gcr-internal:
        machine: true
        steps:
            - setup_environment
            - checkout
            # We can't use Bash variables in CircleCI so we just duplicate the ""./dockerconfig.json"
            # string here.
            - run: echo "${GCLOUD_SERVICE_ACCOUNT_SINGLESTORE_PUBLIC}" | base64 -d >./dockerconfig.json
            - run: cat ./dockerconfig.json | docker login -u _json_key --password-stdin https://gcr.io
            - run: make build-node redhat-verify-ubi-gcr-internal-node VARIANT=redhat

workflows:
    test_publish:
        jobs:
            - test

            - publish-dockerhub:
                  name: publish-dockerhub-<< matrix.package >>
                  type: approval
                  matrix:
                      parameters:
                          # Must match line 71.
                          package:
                              [
                                  "node",
                                  "node-preview",
                                  "node-6-8",
                                  "node-7-0",
                                  "node-7-1",
                                  "node-7-3",
                                  "node-7-5",
                                  "node-7-6",
                                  "dynamic-node",
                                  "ciab",
                                  "tools",
                              ]
                  requires:
                      - test

            - publish-redhat:
                  name: publish-redhat-<< matrix.package >>
                  type: approval
                  matrix:
                      parameters:
                          # Must match line 93.
                          package:
                              [
                                  "node",
                                  "node-7-0",
                                  "node-7-1",
                                  "node-7-3",
                                  "node-7-5",
                                  "node-7-6",
                              ]
                  requires:
                      - test

            - publish-redhat-ciab:
                  name: publish-redhat-ciab
                  type: approval
                  requires:
                      - test

            - dockerhub:
                  name: dockerhub-<< matrix.package >>
                  matrix:
                      parameters:
                          package:
                              [
                                  "node",
                                  "node-preview",
                                  "node-6-8",
                                  "node-7-0",
                                  "node-7-1",
                                  "node-7-3",
                                  "node-7-5",
                                  "node-7-6",
                                  "dynamic-node",
                                  "ciab",
                                  "tools",
                              ]
                  requires:
                      - publish-dockerhub-<< matrix.package >>

            - redhat:
                  name: redhat-<< matrix.package >>
                  matrix:
                      parameters:
                          package:
                              [
                                  "node",
                                  "node-7-0",
                                  "node-7-1",
                                  "node-7-3",
                                  "node-7-5",
                                  "node-7-6",
                                  
                              ]
                  requires:
                      - publish-redhat-<< matrix.package >>

            - redhat-ciab:
                  name: redhat-ciab
                  requires:
                      - publish-redhat-ciab

            - publish-ubi-gcr-internal:
                  name: publish-ubi-gcr-internal
                  type: approval
                  requires:
                      - test

            - ubi-gcr-internal:
                  name: ubi-gcr-internal
                  requires:
                      - publish-ubi-gcr-internal

            - publish-gcr-public:
                  name: publish-gcr-public-<< matrix.package >>
                  type: approval
                  matrix:
                      parameters:
                          # Must match line 71.
                          package:
                              [
                                  "node-cloud",
                              ]
                  requires:
                      - test

            - gcr-public:
                name: gcr-public-<< matrix.package >>
                matrix:
                    parameters:
                        package:
                            [
                                "node-cloud",
                            ]
                requires:
                    - publish-gcr-public-<< matrix.package >>

