version: 2.1

commands:
    setup_environment:
        description: "Setup the machine environment"
        steps:
            - run: |
                  sudo apt update
                  sudo apt install -y make bash git jq docker

jobs:
    test:
        machine: true
        steps:
            - setup_environment
            - checkout
            - run: make test
            - run: make test-destroy

    redhat:
        parameters:
            package:
                type: string
        machine: true
        steps:
            - setup_environment
            - checkout
            - run: docker login -u unused --password ${REDHAT_REGISTRY_KEY_NODE} scan.connect.redhat.com
            - run: make build-<<parameters.package>> redhat-verify-<<parameters.package>> VARIANT=redhat

    redhat-ciab:
        machine: true
        steps:
            - setup_environment
            - checkout
            - run: docker login -u unused --password ${REDHAT_REGISTRY_KEY_CIAB} scan.connect.redhat.com
            - run: make build-ciab redhat-verify-ciab VARIANT=redhat

    dockerhub:
        parameters:
            package:
                type: string
        machine: true
        steps:
            - setup_environment
            - checkout
            - run: docker login -u ${DOCKER_HUB_USER} --password ${DOCKER_HUB_KEY}
            - run: make build-<<parameters.package>> publish-<<parameters.package>>

workflows:
    test_publish:
        jobs:
            - test

            - dockerhub:
                name: dockerhub-<< matrix.package >>
                requires:
                    - test
                matrix:
                    parameters:
                        package:
                            [
                                "node",
                                "node-6-5",
                                "node-6-8",
                                "node-7-0",
                                "node-7-1",
                                "node-7-3",
                                "dynamic-node",
                                "ciab",
                                "tools",
                            ]

            - redhat:
                  name: redhat-<< matrix.package >>
                  matrix:
                      parameters:
                          package: ["node", "node-7-0", "node-7-1", "node-7-3"]
                  requires:
                      - test

            - redhat-ciab:
                  name: redhat-ciab
                  requires:
                      - test
